services:
  database:
    image: postgres
    container_name: lifecheatsheet_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: life-cheatsheet
    ports:
      - '5432:5432'
  database-redis:
    image: redis
    container_name: lifecheatsheet_redis
    restart: always
    ports:
      - '6379:6379'
