app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/life-cheatsheet
      username: postgres
      password: docker
      pool-size: 30